### ISSUE TITLE
Example that is given is crap, this one is better

### ISSUE THREAD

**Issue by rcaweb** [callumlocke/grunt-cdnify#10]
someTarget: {} shouldn't surround options, it should be after options. I made "dist" my "someTarget"
Following this example given sent me on a wild goose chase. This one below is the proper syntax.
<pre>
<code>
cdnify: {
      options: {
          rewriter: function (url) {
          		        var filename = url.substring(url.lastIndexOf('/')+1);
		  		var fileExt = filename.split('.').pop();
				if( fileExt == 'jpg' )
					return '//cdn.domain.com/' + filename;
				else
					return url;
          }
        },
        dist: {
          expand: true,
          src: 'assets/**/*.css',
          dest: '',
        }
	}
  });
</code>
</pre>

**Comment by billpatrianakos** [comment]
No, this issue should be closed. The example here will look for all files called ".css" inside of `assets/`. I'm also not keen to follow the advice of someone who doesn't properly format code where markdown is supported.

**Comment by rcaweb** [comment]
there you go

**Comment by callumlocke** [comment]
> someTarget: {} shouldn't surround options, it should be after options.

no, options can be per-target. see http://gruntjs.com/configuring-tasks#options
