### ISSUE TITLE
Not replacing background-image url in css

### ISSUE THREAD

**Issue by tjwudi** [callumlocke/grunt-cdnify#11]
I am using grunt-cdnify with my project and I found that it doesn't actually replacing `background-image` url in css. But it works for `background` url.

![screen shot 2014-09-17 at 11 02 24 am](https://cloud.githubusercontent.com/assets/5257816/4297939/25867008-3e17-11e4-99ee-888e40ea65d0.png)

**Comment by seb0zz** [comment]
+1

**Comment by chrisocast** [comment]
+1

**Comment by reacher-lu** [comment]
+1024

**Comment by XhmikosR** [comment]
#11
