### ISSUE TITLE
Relative path links are CDNified incorrectly

### ISSUE THREAD

**Issue by kudresov** [callumlocke/grunt-cdnify#14]
If the resource had a relative path it is overwritten incorrectly as a result you get: 
`<script src="../..//ajax.googleapis.com/ajax/libs/angularjs/1.2.23/angular-resource.min.js"></script>`

**Comment by lyio** [comment]
Is there a way to ignore specific relative paths? I ran into the same problem recently.

**Comment by XhmikosR** [comment]
Does this still happen with the latest master?

**Comment by XhmikosR** [comment]
Closing this since it should be fixed in the latest version. Feel free to comment if not.
