### ISSUE TITLE
shortcut icon links are not rewritten

### ISSUE THREAD

**Issue by soulrebel** [callumlocke/grunt-cdnify#16]
Title says it all. Here's an example:

    <link rel="shortcut icon" type="image/png" href="images/favicon.e29d6f41.png">

**Comment by guncha** [comment]
Seeing the same issue here :+1:

**Comment by guncha** [comment]
There's a configuration option that let's you specify which HTML elements to process. For me, I had to add something like this:

```javascript
html: {
  'link[rel="shortcut icon"]': 'href'
}
```

It would probably make a good default.

More info: https://github.com/callumlocke/grunt-cdnify#html-booleanobject

**Comment by callumlocke** [comment]
Yes it would be a good default, PR :+1:

**Comment by XhmikosR** [comment]
https://github.com/callumlocke/grunt-cdnify/commit/cbb120bbb620e0c769660b078f9cc088892d4052
