### ISSUE TITLE
New maintainer needed

### ISSUE THREAD

**Issue by callumlocke** [callumlocke/grunt-cdnify#19]
I don't use grunt any more. Does anyone want to take over this repo?

**Comment by alexandrusavin** [comment]
I could give it a try. I will use it in production soon so I'm able to maintain it. I already have a pr here: https://github.com/callumlocke/grunt-cdnify/pull/21

**Comment by Climax777** [comment]
Has someone taken over maintenance yet?

**Comment by XhmikosR** [comment]
@callumlocke: I could do it since I'm using the plugin.
