### ISSUE TITLE
Support templating languages like Jade

### ISSUE THREAD

**Issue by JaKXz** [callumlocke/grunt-cdnify#24]
Please and thank you!

**Comment by callumlocke** [comment]
Sorry, I can't see point in cdn-ifying URLs before rendering templates. Better to convert your Jade to HTML using another plugin, and then use this one to modify the URLs.

**Comment by klassicd** [comment]
Many web application frameworks (e.g. Express) render jade files in real time.  If you don't optimize for performance, and use the default functionality, you end up with 100% jade builds in which case supporting this feature would be helpful.   I hope you change your mind and in the mean time I'll be using https://www.npmjs.com/package/grunt-local2cdn
