### ISSUE TITLE
Relative paths to parent dirs (../../) are not resolved correctly

### ISSUE THREAD

**Issue by alfredbaudisch** [callumlocke/grunt-cdnify#27]
In my CSS I have a bunch of styles which have background-images pointing to a relative path:

```css
background-image: url('../../images/email_icon.png');
background-image: url('../../images/igrejas_icon.png');
background-image: url('../../images/perfil_icon.png');
```

After running cdnify some paths are set with random/messed up URLs while other's aren't modified at all:
```css
background-image:url(http://pocketchurch/images/fb_icon.png);
background-image:url(../../images/email_icon.png);
background-image: url(http://pocketchurch/../../images/perfil_icon.png);
```

The base is supposed to be `http://pocketchurch/admin/dist/` but it is never placed:
```js
        cdnify: {
            dist: {
                options: {
                    base: 'http://pocketchurch/admin/dist/'
                },
                files: [{
                    expand: true,
                    cwd: 'dist',
                    src: '**/*.{css,html}',
                    dest: 'dist'
                }]
            }
        },
```

**Comment by zmpandzmp** [comment]
+1，and my config is :
cdnify: {
			replace: {
				options: {
					rewriter: function (url) {
						var base = 'http://msgcoder.oss-cn-beijing.aliyuncs.com/20150910%2F';
						if (url != '') {
							url = url.replace(/\.\.\//g, '');
							url = url.replace(/\//g, '%2F');
							console.log('log:    ' + url + '   changed to      ' + base + url);
							return base + url;
						} else {
							return '';
						}
					}
				},
				files: [{
					expand: true,
					cwd: '<%=config.dist %>',
					src: '**/*.{css,html}',
					dest: '<%=config.dist%>'
				}]
			}
		}

**Comment by zmpandzmp** [comment]
+1

**Comment by XhmikosR** [comment]
This should be fixed by https://github.com/callumlocke/grunt-cdnify/pull/28. If not leave a comment here.
