### ISSUE TITLE
1.0.1 regression

### ISSUE THREAD

**Issue by XhmikosR** [callumlocke/grunt-cdnify#30]
https://github.com/callumlocke/grunt-cdnify/commit/3d3edeb3401a3db4612335907a25f760ff81492c#commitcomment-13831907

**Comment by XhmikosR** [comment]
This seems to be caused by the `url` switch in https://github.com/callumlocke/grunt-cdnify/pull/28. Reverting this works again.

Not sure if we should just revert. I'm trying to understand why it fails but I don't see it yet :/

**Comment by callumlocke** [comment]
want me to add you as an owner on npm so you can publish another patch when you figure it out? do you have an npm username?

**Comment by XhmikosR** [comment]
So it seems it's empty for `link rel"stylesheet"'`

```
Running "cdnify:defaultOptions" (cdnify) task
ret:  //cdn.example.com/stuff/foo.jpg
ret:  //cdn.example.com/foo.jpg
ret:  //cdn.example.com/foo/bar/test.jpg
ret:  //cdn.example.com/foo/bar/test.jpg
ret:  //cdn.example.com/foo.jpg
ret:  //cdn.example.com/stuff/foo/bar.jpg
ret:  //cdn.example.com/stuff/bar.jpg
ret:  //cdn.example.com/stuff/foo.jpg
ret:  //cdn.example.com/stuff/foo
ret:  //cdn.example.com/stuff/blah.png
ret:  //cdn.example.com/stuff/bar.jpg
ret:
ret:  //cdn.example.com/favicon.ico
ret:  //cdn.example.com/apple-touch-icon.png
ret:  //cdn.example.com/stuff/hello.js
ret:  //cdn.example.com/stuff/foo.jpg
ret:  //cdn.example.com/foo.jpg
ret:  //cdn.example.com/foo.jpg
ret:  //cdn.example.com/stuff/foo/bar.jpg
>> Wrote 1 CSS file
>> Wrote 1 HTML file

Running "cdnify:customOptions" (cdnify) task
ret:  //cdn.example.com/stuff/abc.jpg
ret:  //cdn.example.com/stuff/foo
ret:
ret:  //cdn.example.com/favicon.ico
ret:  //cdn.example.com/apple-touch-icon.png
ret:  //cdn.example.com/stuff/hello.js
ret:  //cdn.example.com/stuff/foo.jpg
ret:  //cdn.example.com/foo.jpg
ret:  //cdn.example.com/foo.jpg
ret:  //cdn.example.com/stuff/foo/bar.jpg
>> Wrote 1 HTML file
```

My npm username is `xhmikosr` but I haven't made any npm release myself yet.

My concern is to fix this and publishing is the last thing :)

**Comment by XhmikosR** [comment]
All right, it seems the problem happens when `isLocalPath` is used; `url` is fine.

**Comment by XhmikosR** [comment]
Ah, stupid me...

**Comment by XhmikosR** [comment]
@callumlocke: please make a 1.0.2 and sorry for the regression, I totally missed it.

**Comment by XhmikosR** [comment]
@callumlocke: a friendly ping for the bugfix release :)

**Comment by callumlocke** [comment]
done, thanks for all your help with this!

let me know your npm username if you want me to add you as a package owner, so you can publish new versions.

**Comment by XhmikosR** [comment]
My npm username is `xhmikosr`. I doubt I'll make any release myself since I always prefer to discuss changes beforehand, but you never know :)
